name: OmniToken CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install dependencies
      run: |
        pip install maturin pytest hypothesis
        pip install tokenizers tiktoken
    - name: Build and install
      run: |
        cd python/omnitoken
        maturin develop
    - name: Test Python
      run: |
        cd python/omnitoken
        pytest
